version: "3.9"
services:
  app:
    restart: always
    container_name: video-api
    build: .
    volumes:
      - ./app:/app/
      - ./downloads:/app/downloads/
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    command: uvicorn main:app --host 0.0.0.0 --port 8080  --reload --access-log --use-colors
    ports:
      - "8080:8080"
