version: "3.9"
services:
  app:
    restart: always
    container_name: video-api
    build: .
    volumes:
      - ./src:/src/
      - ./poetry.lock:/src/poetry.lock
      - ./pyproject.toml:/src/pyproject.toml
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --workers 4  --reload --access-log --use-colors
    ports:
      - "8080:8080"
